export const UPLOAD_ART_REQUEST = 'UPLOAD_ART_REQUEST'
export const UPLOAD_ART_SUCCESS = 'UPLOAD_ART_SUCCESS'
export const UPLOAD_ART_FAIL = 'UPLOAD_ART_FAIL'


export const GET_ALL_ARTS_REQUEST = 'GET_ALL_ARTS_REQUEST'
export const GET_ALL_ARTS_SUCCESS = 'GET_ALL_ARTS_SUCCESS'
export const GET_ALL_ARTS_FAIL = 'GET_ALL_ARTS_FAIL'


export const GET_USER_ARTS_REQUEST = 'GET_USER_ARTS_REQUEST'
export const GET_USER_ARTS_SUCCESS = 'GET_USER_ARTS_SUCCESS'
export const GET_USER_ARTS_FAIL = 'GET_USER_ARTS_FAIL'


export const DELETE_USER_ART_REQUEST = 'DELETE_USER_ART_REQUEST'
export const DELETE_USER_ART_SUCCESS = 'DELETE_USER_ART_SUCCESS'
export const DELETE_USER_ART_FAIL = 'DELETE_USER_ART_FAIL'


export const LOAD_ART_REQUEST = 'LOAD_ART_REQUEST'
export const LOAD_ART_SUCCESS = 'LOAD_ART_SUCCESS'
export const LOAD_ART_FAIL = 'LOAD_ART_FAIL'