export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'


export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'


export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const VERIFY_USER_EMAIL_REQUEST = 'VERIFY_USER_EMAIL_REQUEST'
export const VERIFY_USER_EMAIL_FAIL = 'VERIFY_USER_EMAIL_FAIL'
export const VERIFY_USER_EMAIL_SUCCESS = 'VERIFY_USER_EMAIL_SUCCESS'
export const CLEAR_USER_EMAIL_VERIFY_ERRORS = 'CLEAR_USER_EMAIL_VERIFY_ERRORS'
export const USER_EMAIL_VERIFIED = 'USER_EMAIL_VERIFIED'


export const UPDATE_USER_DETAIL_REQUEST = 'UPDATE_USER_DETAIL_REQUEST'
export const UPDATE_USER_DETAIL_FAIL = 'UPDATE_USER_DETAIL_FAIL'
export const UPDATE_USER_DETAIL_SUCCESS = 'UPDATE_USER_DETAIL_SUCCESS'
export const UPDATE_USER_DETAILS_DONE = 'UPDATE_USER_DETAILS_DONE'
export const UPDATE_USER_DETAILS_CLEAR_ERRORS = 'UPDATE_USER_DETAILS_CLEAR_ERRORS'